reviewers:
  # The default reviewers
  defaults:
    - core

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    core:
      - kgodey
      - mathemancer
      - pavish
      - seancolsen
      - ghislaineguerin
      - eito-fis
      - silentninja

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - core

options:
  ignore_draft: true
  enable_group_assignment: false
